### PR TITLE
feat: add valaxy-addon-image package

### PR DESCRIPTION
**Pull request by hairyf**
#99
# valaxy-addon-image

Support image group browsing, and more properties

```ts
import { defineConfig } from 'valaxy'
export default defineConfig({
  addons: [
    'valaxy-addon-image'
  ]
})
```

## Use alone

```md
## image

<Image fit="cover" style="width: 100px; height: 100px" src="https://fuss10.elemecdn.com/e/5d/4a731a90594a4af544c0c25941171jpeg.jpeg" />

```
## Image group

Use group click on image to pop up preview overlay

```md
## images

<ImageGroup gap="12" row="120px">
  <Image src="https://tva2.sinaimg.cn/large/6833939bly1gicitcxhpij20zk0m8hdt.jpg" />
  <Image src="https://tva2.sinaimg.cn/large/6833939bly1gicitf0kl1j20zk0m87fe.jpg" />
  <Image src="https://tva2.sinaimg.cn/large/6833939bly1gicitht3xtj20zk0m8k5v.jpg" />
  <Image src="https://tva2.sinaimg.cn/large/6833939bly1gicitspjpbj20zk0m81ky.jpg" />
  <Image src="https://tva2.sinaimg.cn/large/6833939bly1gicitzannuj20zk0m8b29.jpg" />
  <Image src="https://tva2.sinaimg.cn/large/6833939bly1giciub8ja1j20zk0m81ky.jpg" />
  <Image src="https://tva2.sinaimg.cn/large/6833939bly1giciuja1j1j20zk0m8kjl.jpg" />
</ImageGroup>

```

click on image

image

## ImageGroup Attributes

- row(`number/string`) row width
- col(`number/string`) col height
- gap(`number/string`) spacing
- justify   (`string`) [justify-content](https://developer.mozilla.org/zh-CN/docs/Web/CSS/justify-content) shorthand
- align     (`string`) [align-items](https://developer.mozilla.org/zh-CN/docs/Web/CSS/align-items) shorthand

## Image Attributes

you can [element-plus/image](https://element-plus.gitee.io/en-US/component/image.html#image)

### CODE REVIEW

**Comment by YunYouJun** [comment]
The element-plus image-viewer is a bit heavy to use, users can also use this component directly when they want to use it.

I think `valaxy-addon-images` should come from a lighter and more specialized library, or integrate directly into valaxy.

**Comment by YunYouJun** [comment]
[lightgallery](https://www.npmjs.com/package/lightgallery) looks good.

**Comment by YunYouJun** [comment]
[medium-zoom](https://github.com/francoischalifour/medium-zoom)(light) can be integrated in valaxy.
[lightgallery](https://github.com/sachinchoolur/lightGallery) can be an addon `valaxy-addon-lightgallery`.

**Comment by TuiMao233** [comment]
It looks good. I will support it

**Comment by YunYouJun** [comment]
`lightgallery.ts:240 lightGallery: 0000-0000-000-0000 license key is not valid for production use`.

Even though valaxy is not a business project, lightgallery had such a warning that I had to give it up.

https://github.com/sachinchoolur/lightGallery/issues/1022

**Comment by YunYouJun** [comment]
https://photoswipe.com/ 

Photoswipe seems good.

**Comment by YunYouJun** [comment]
I create a `valaxy-addon-lightgallery`. It seems to work well.

> https://yun.valaxy.site/albums

**Comment by TuiMao233** [comment]
I don't think it seems very difficult here. I think we can create a variety of application scenarios ourselves that support Valaxy, do you think?

```html
<image-gruop width="xxx" height="xxx">

## xxxx

xxx

<image src="xxx" fall-src="xxx" />

> xxxx

<image src="xxx" fall-src="xxx" />

</image-group>
```
The above is a simple template, and we are discussing the more detailed API

What's your opinion? If there is no problem, I will create a new request again and confirm that the work is being carried out correctly (to avoid wasting time

**Comment by YunYouJun** [comment]
Thanks for your work.

I think [valaxy-addon-lightgallery](https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-addon-lightgallery) should have met your needs.
I will close this issue. If you think there is any deficiency, please let us discuss it again.

**Pull request closed without merging**
