### PR TITLE
feat: encrypt partial content

### PR DESCRIPTION
**Pull request by yixiaojiu**
### Description

The current implementation still has some issues, since I don't know how to recurse components in `ValaxyDecrypt`, I created `ValaxyPartiallyDecrypt.vue`, some code is not reused

### Linked Issues

https://github.com/YunYouJun/valaxy/issues/249

### Example Page

https://valaxy-docs-dev-git-fork-yixiaojiu-encrypt-yunyoujun.vercel.app/examples/partial-content-encryption

### Copilot Descriptions

copilot:all

### CODE REVIEW

**Review by YunYouJun — APPROVED** [review]

**Comment by YunYouJun** [comment]
That's cool.

I feel that for the sake of brevity, when the user has enabled full-text encryption, we should ignore the internal portion of the encrypted content without special treatment.

**Comment by YunYouJun** [comment]
What do you think? From this perspective, do we need two more components?

**Comment by yixiaojiu** [comment]
> That's cool.
> 
> I feel that for the sake of brevity, when the user has enabled full-text encryption, we should ignore the internal portion of the encrypted content without special treatment.

I'm glad you invited me into the organization. This case really doesn't need two components. I will fix implementation next Monday.

**Comment by yixiaojiu** [comment]
I have fixed the implementation. Could you review it again?

**Review by YunYouJun — APPROVED** [review]

**Comment by YunYouJun** [comment]
Looks good! I will release it together this Friday.

**Pull request merged**
