### PR TITLE
feat: integrate bilibili-bangumi-component

### PR DESCRIPTION
**Pull request by yixiaojiu**
### Problem

`bilibili-bangumi` is a custom component, and Vue will display a warning. However, I am unsure about how to modify this configuration in the plugin hook.

https://github.com/YunYouJun/valaxy/blob/3c40926a6ebb0d93cd38b2ec58b00a81e6b7e7d0/packages/valaxy/node/plugins/preset.ts#L80-L82

### CODE REVIEW

**Comment by YunYouJun** [comment]
Why close it?

**Comment by yixiaojiu** [comment]
image

There is an error when building for SSG. The ESM module is being mistakenly identified as CJS. This is the repo and branch:
 https://github.com/yixiaojiu/valaxy/tree/bangumi

**Comment by YunYouJun** [comment]
Maybe you can pack them to be `mjs/cjs`.

**Comment by yixiaojiu** [comment]
Not working 😭. I have trying many methods.

**Comment by YunYouJun** [comment]
Wrap it with `ClientOnly`.

**Pull request closed without merging**
