### PR TITLE
feat: Footnote tooltip

### LINKED ISSUE #416: Markdown footnote tooltip
### Clear and concise description of the problem

Markdown 默认的 footnote 为底部内容的跳转。

### Suggested solution

支持通过鼠标悬浮的方式直接展示脚标提示。

Supports the direct display of the footnote tooltip through the mouse hover.

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by BlueGlassBlock**
### Description

Adds hover tooltips for footnotes.

### Linked Issues

Close #416

### Additional context

- [x] e2e test
- [x] Configuration for Floating Vue integration
### Copilot Descriptions

copilot:all

### CODE REVIEW

**Comment by YunYouJun** [comment]
I guess it should work, can you add an e2e test for this?

**Comment by YunYouJun** [comment]
Is it working at the moment? Ready to merge?

**Comment by BlueGlassBlock** [comment]
I think it's good to go.

**Comment by YunYouJun** [comment]
`pnpm-lock.yaml` conflicts need to be resolved.

**Pull request merged**
