### PR TITLE
feat: integrate bilibili-bangumi-component

### PR DESCRIPTION
**Pull request by yixiaojiu**
### Problem

`bilibili-bangumi` is a custom component, and Vue will display a warning. However, I am unsure about how to modify this configuration in the plugin hook.

https://github.com/YunYouJun/valaxy/blob/3c40926a6ebb0d93cd38b2ec58b00a81e6b7e7d0/packages/valaxy/node/plugins/preset.ts#L80-L82

### CODE REVIEW

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/valaxy/commit/1e1ba90847872ace332595131cd3555066455d09

I export `customElements`. You can `import customElements` and `customElements.add()`.

**Comment by yixiaojiu** [comment]
> [1e1ba90](https://github.com/YunYouJun/valaxy/commit/1e1ba90847872ace332595131cd3555066455d09)
> 
> I export `customElements`. You can `import customElements` and `customElements.add()`.

It's not working! I added a new value to `customElements`, but I can't retrieve the new value in `isCustomElement` 😨.

**Comment by yixiaojiu** [comment]
It appears that `valaxy/packages/valaxy/node/plugins/preset.ts` is being loaded multiple times, which is causing the customElements to be reset.

**Comment by yixiaojiu** [comment]
How about exporting a `customElements` configuration for this?

https://github.com/YunYouJun/valaxy/blob/1e1ba90847872ace332595131cd3555066455d09/packages/valaxy/node/types.ts#L86

**Comment by YunYouJun** [comment]
> It appears that `valaxy/packages/valaxy/node/plugins/preset.ts` is being loaded multiple times, which is causing the `customElements` to be reset.

Oops, maybe it will works.

image

```ts
    Vue({
      include: [/\.vue$/, /\.md$/],
      exclude: [],
      template: {
        compilerOptions: {
          isCustomElement: (tag) => {
            return customElements.has(tag) || valaxyConfig.vue?.template?.compilerOptions?.isCustomElement?.(tag)
          },
        },
        ...valaxyConfig.vue?.template,
      },
      ...valaxyConfig.vue,
    }),
```

**Comment by yixiaojiu** [comment]
https://github.com/YunYouJun/valaxy/blob/5e6b6c2f804e4bf4b7040c73dba57420fbbc029a/packages/valaxy/node/plugins/preset.ts#L36-L49

It doesn't look like it will work because the configuration will be overwritten by line 49. If many addons are configured with `isCustomElement`, only one addon's `isCustomElement` will take effect, and the 44 lines of code will become invalid.

**Comment by YunYouJun** [comment]
```ts
      template: {
        compilerOptions: {
          isCustomElement: (tag) => {
            let is = customElements.has(tag)
            valaxyConfig.vue?.isCustomElement?.forEach((fn) => {
              is = is || fn(tag)
            })
            return is
          },
        },
      },
```

```ts
import { defineValaxyConfig } from 'valaxy'

export default defineValaxyConfig({
  vue: {
    isCustomElement: [
      (tag) => {
        return tag === 'meting-js'
      },
    ],
  },
})
```

It works now.

**Pull request closed without merging**
