### PR TITLE
feat: collapse for code

### PR DESCRIPTION
**Pull request by yixiaojiu**
### Linked Issues

https://github.com/YunYouJun/valaxy/issues/262

### Copilot Descriptions

copilot:all

### CODE REVIEW

**Comment by YunYouJun** [comment]
Hey, it seems cool.
Can you add an example page in `docs/pages/examples/xxx.md`?

I wish we could preview it directly.

**Comment by yixiaojiu** [comment]
> Hey, it seems cool.
> Can you add an example page in `docs/pages/examples/xxx.md`?
> 
> I wish we could preview it directly.
> 

Oh, sorry. I forgot to add an example. Additionally, I have not implemented frontmatter configuration, and I may complete it tomorrow.

**Comment by yixiaojiu** [comment]
This is the [sample page](https://valaxy-docs-b1rom8r9r-yunyoujun.vercel.app/examples/code-height-limit), and the css is  simple.

**Comment by YunYouJun** [comment]
Thanks for your contribution!

I fix dark mode & add some test/docs in https://github.com/YunYouJun/valaxy/commit/3d9831ef95ceda37ad3f08fff3287e9538c518f9.

**Comment by YunYouJun** [comment]
close #262

**Pull request merged**
